name: DVC Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_dvc_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install dvc

      - name: Initialize DVC pipeline
        run: dvc init -f
      - name: Add to dvc
        run: |
              dvc remote add -d https://drive.google.com/drive/u/1/folders/17qkHKj1qKIc3cG5UA1AiPgWdp4rJdXTp
        
